import { Metadata } from 'next'
import { ReactNode } from 'react'
import BrandImage from '@/assets/images/logo.svg'
import { NavItems } from '@/components/pages/dashboard/nav-items'
import UserDropdown from '@/components/pages/dashboard/user-dropdown'
import { ThemeToggle } from '@/components/shared/theme-provider/theme-toggle'

export const metadata: Metadata = {
    title: 'Dashboard | Home',
    description: 'Generated by create next app',
}

export default function DashboardLayout({ children }: { children: ReactNode }) {
    return (
        <div className="w-full h-screen overflow-hidden grid grid-cols-[300px,1fr]">
            <aside className="w-full h-full flex flex-col items-center border-r border-muted">
                <div className="w-full p-6 border-b border-muted">
                    <BrandImage className="max-w-[100px] mx-auto" />
                </div>
                <NavItems />
                <div className="w-full mt-auto border-t border-muted px-3 py-4 flex items-center justify-between gap-2">
                    <UserDropdown />
                    <ThemeToggle />
                </div>
            </aside>
            <main className="p-6 flex flex-col w-full h-full overflow-auto">
                {children}
            </main>
        </div>
    )
}
