import { Metadata } from 'next'
import { ReactNode } from 'react'
import BrandImage from '@/assets/images/logo.svg'

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default function DashboardLayout({ children }: { children: ReactNode }) {
    return (
        <div className="w-full h-screen overflow-hidden grid grid-cols-[300px,1fr]">
            <aside className="w-full h-full flex flex-col items-center border-r border-muted">
                <div className="w-full p-6 border-b border-muted">
                    <BrandImage className="max-w-[100px] mx-auto" />
                </div>
            </aside>
            <main className="w-full">{children}</main>
        </div>
    )
}
